---
abstract: 'Create tickets in OTRS via the Command Line Interface.'
author:
  - 'Michiel Beijen <michiel.beijen@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-OTRS-CreateTicket
requires:
  GetOpt::Long: 0
  Pod::Usage: 0
  SOAP::Lite: 0
resources:
  bugtracker: https://github.com/mwb/App-OTRS-CreateTicket/issues
  homepage: https://github.com/mwb/App-OTRS-CreateTicket
  repository: https://github.com/mwb/App-OTRS-CreateTicket.git
version: 1.0.1
